### ISSUE TITLE
About Code Release

### ISSUE THREAD

**Issue by xiaolul2** [ShanWang-Shan/HomoFusion#1]
Thanks for your interesting work! 
I'm looking forward to your code!

**Comment by ShanWang-Shan** [comment]
Thank you for your interest in my work. Currently, this work is under the review of a patent application by CSIRO. I will publish the source code once I receive approval for publishing. Thank you for your patience.

**Comment by ShanWang-Shan** [comment]
Sorry for the delay; the source code has been committed.

**Comment by ShanWang-Shan** [comment]
Closed as the requirement has been satisfied.
